### PostMapping - POST transform/save-transformation
POST http://localhost:8080/transform/save-transformation
Content-Type: application/json
Accept: application/json

{
  "sampleField": "value",
  "anotherField": 123
}
