name: Build and Generate Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-executables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build Spring Boot App
        run: |
          cd spring-ftl
          mvn clean package
        working-directory: ${{ github.workspace }}

      - name: Move Spring Boot JAR to root
        run: |
          cp spring-ftl/target/*.jar spring-boot-app.jar

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}/py-xmlgen

      - name: Build Python Executable with PyInstaller
        run: |
          pyinstaller main.spec
        working-directory: ${{ github.workspace }}/py-xmlgen

      - name: Move Python Executable to root
        run: |
          cp py-xmlgen/dist/main main-executable

      - name: Start Spring Boot App in background
        run: |
          nohup java -jar spring-boot-app.jar > spring.log 2>&1 &
          sleep 10

      - name: Test Spring Boot endpoint
        run: |
          curl --fail http://localhost:8080/actuator/health

      - name: Test Python Executable
        run: |
          ./main-executable --help

      - name: Archive built executables
        uses: actions/upload-artifact@v4
        with:
          name: release-archives
          path: |
            spring-boot-app.jar
            main-executable
          retention-days: 90

      - name: Generate README artifact (optional)
        run: |
          echo "# Build Artifacts" > README_BUILD.md
          echo "" >> README_BUILD.md
          echo "- Spring Boot JAR: spring-boot-app.jar" >> README_BUILD.md
          echo "- Python Executable: main-executable" >> README_BUILD.md
        shell: bash

      - name: Upload README artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-readme
          path: README_BUILD.md
          retention-days: 90
